services:
  redocly:
    image: redocly/redoc
    volumes:
      - ~/Projects/prosa/openapi/:/usr/share/nginx/html/swagger/
    environment:
      - SPEC_URL=swagger/openapi.yaml
      - REDOC_OPTIONS=hide-download-button
    ports:
      - "8080:80"
