[server]
host = "0.0.0.0"
port = 5000

[auth]
secret_key = "jwt_secret_key"
admin_key = "admin_key"
jwt_token_duration = 900
refresh_token_duration = 604800
allow_user_registration = true

[book_storage]
epub_path = "library/epubs"
cover_path = "library/covers"

[metadata_cooldown]
goodreads = 1000
epub_extractor = 0

[database]
file_path = "library/database.db"

[kepubify]
path = "kepubify/kepubify"