name: Build & Test

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build server
        run: cargo build --release

      - name: Download kepubify
        run: |
          mkdir -p kepubify
          curl -s https://api.github.com/repos/tiago-cos/kepubify/releases/latest \
            | grep "browser_download_url.*kepubify-linux-64bit" \
            | cut -d '"' -f 4 \
            | xargs curl -L -o kepubify/kepubify
          chmod +x kepubify/kepubify


      - name: Run server in background
        run: |
          ./target/release/prosa &
          SERVER_PID=$!
          echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
          sleep 5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: tests/package-lock.json

      - name: Install test deps
        working-directory: tests
        run: npm ci

      - name: Run Jest tests
        working-directory: tests
        run: npm test

      - name: Kill server
        if: always()
        run: kill $SERVER_PID || true
